// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TisaWasteManagement.Data;

#nullable disable

namespace TisaWasteManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821030756_SQLiteInitialCreate")]
    partial class SQLiteInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("TisaWasteManagement.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.BulletinBoardImage", b =>
                {
                    b.Property<int>("BulletinBoardImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BulletinBoardImageId");

                    b.ToTable("BulletinBoardImage", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionMonitoring", b =>
                {
                    b.Property<int>("CollectionMonitoringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonForDelay")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SitioNames")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionMonitoringId");

                    b.HasIndex("CollectionScheduleId");

                    b.ToTable("CollectionMonitoring", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionSchedule", b =>
                {
                    b.Property<int>("CollectionScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfCompletion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DumpNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepeatWeekly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TruckId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionScheduleId");

                    b.HasIndex("DriverId");

                    b.HasIndex("ParentScheduleId");

                    b.HasIndex("TruckId");

                    b.ToTable("CollectionSchedule", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionScheduleCollector", b =>
                {
                    b.Property<int>("CollectionScheduleCollectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollectionScheduleCollectorId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("CollectionScheduleId", "CollectorId")
                        .IsUnique();

                    b.ToTable("CollectionScheduleCollector", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionScheduleSitio", b =>
                {
                    b.Property<int>("CollectionScheduleSitioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonForDelay")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReassignedToScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SitioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionScheduleSitioId");

                    b.HasIndex("SitioId");

                    b.HasIndex("CollectionScheduleId", "SitioId")
                        .IsUnique();

                    b.ToTable("CollectionScheduleSitio", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.Collector", b =>
                {
                    b.Property<int>("CollectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysOff")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CollectorId");

                    b.HasIndex("ContactNumber")
                        .IsUnique();

                    b.ToTable("Collector", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComplaintType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidentName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SitioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Awaiting Review");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ComplaintId");

                    b.HasIndex("SitioId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("Complaint", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.GarbageTruck", b =>
                {
                    b.Property<int>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MVFileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusFlag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TruckId");

                    b.HasIndex("MVFileNumber")
                        .IsUnique();

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("GarbageTruck", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.InspectorAccount", b =>
                {
                    b.Property<int>("InspectorAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("InspectorAccountId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("InspectorAccount", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.ReportFile", b =>
                {
                    b.Property<int>("ReportFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("ReportFileId");

                    b.ToTable("ReportFile", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.Sitio", b =>
                {
                    b.Property<int>("SitioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SitioName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SitioId");

                    b.ToTable("Sitio", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.SmsLog", b =>
                {
                    b.Property<int>("SmsLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Response")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SentBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SmsLogId");

                    b.HasIndex("SentDate");

                    b.HasIndex("Status");

                    b.ToTable("SmsLog", (string)null);
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionMonitoring", b =>
                {
                    b.HasOne("TisaWasteManagement.Models.CollectionSchedule", "CollectionSchedule")
                        .WithMany()
                        .HasForeignKey("CollectionScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionSchedule");
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionSchedule", b =>
                {
                    b.HasOne("TisaWasteManagement.Models.Collector", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TisaWasteManagement.Models.CollectionSchedule", "ParentSchedule")
                        .WithMany("ChildSchedules")
                        .HasForeignKey("ParentScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TisaWasteManagement.Models.GarbageTruck", "GarbageTruck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Driver");

                    b.Navigation("GarbageTruck");

                    b.Navigation("ParentSchedule");
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionScheduleCollector", b =>
                {
                    b.HasOne("TisaWasteManagement.Models.CollectionSchedule", "CollectionSchedule")
                        .WithMany("CollectionScheduleCollectors")
                        .HasForeignKey("CollectionScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TisaWasteManagement.Models.Collector", "Collector")
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionSchedule");

                    b.Navigation("Collector");
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionScheduleSitio", b =>
                {
                    b.HasOne("TisaWasteManagement.Models.CollectionSchedule", "CollectionSchedule")
                        .WithMany("CollectionScheduleSitios")
                        .HasForeignKey("CollectionScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TisaWasteManagement.Models.Sitio", "Sitio")
                        .WithMany()
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionSchedule");

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("TisaWasteManagement.Models.Complaint", b =>
                {
                    b.HasOne("TisaWasteManagement.Models.Sitio", "Sitio")
                        .WithMany()
                        .HasForeignKey("SitioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sitio");
                });

            modelBuilder.Entity("TisaWasteManagement.Models.CollectionSchedule", b =>
                {
                    b.Navigation("ChildSchedules");

                    b.Navigation("CollectionScheduleCollectors");

                    b.Navigation("CollectionScheduleSitios");
                });
#pragma warning restore 612, 618
        }
    }
}
