// Services/ReportGenerator.cs
//
// This is where the actual PDF/Excel files get built.
// - PDF generation uses the iTextSharp library (classes like Document, PdfPTable).
// - Excel generation uses the EPPlus library (classes like ExcelPackage).
// Both libraries need to be installed via NuGet - see SETUP_INSTRUCTIONS.md.
using OfficeOpenXml;
using iTextSharp.text;
using iTextSharp.text.pdf;
using TisaWasteManagement.Models;

namespace TisaWasteManagement.Services
{
    public class ReportGenerator : IReportGenerator
    {
        // ---------- Public entry points (called by the controller) ----------

        public byte[] GenerateCollectionReport(CollectionReportData data, string format)
        {
            return format == "Excel"
                ? GenerateCollectionReportExcel(data)
                : GenerateCollectionReportPdf(data);
        }

        public byte[] GenerateComplaintReport(ComplaintReportData data, string format)
        {
            return format == "Excel"
                ? GenerateComplaintReportExcel(data)
                : GenerateComplaintReportPdf(data);
        }

        // ---------- Collection Summary: PDF ----------

        private byte[] GenerateCollectionReportPdf(CollectionReportData data)
        {
            using var stream = new MemoryStream();

            // A4 page with 50pt margins on every side
            var document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.GetInstance(document, stream);
            document.Open();

            var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 11);
            var boldFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);

            document.Add(new Paragraph("COLLECTION SUMMARY REPORT", titleFont) { Alignment = Element.ALIGN_CENTER });
            document.Add(new Paragraph("Barangay Tisa", normalFont) { Alignment = Element.ALIGN_CENTER });
            document.Add(new Paragraph(" "));

            document.Add(new Paragraph($"Generated By: {data.GeneratedBy}", normalFont));
            document.Add(new Paragraph($"Generated On: {data.GeneratedDate:MMMM dd, yyyy h:mm tt}", normalFont));
            document.Add(new Paragraph($"Date Range: {FormatDate(data.StartDate)} - {FormatDate(data.EndDate)}", normalFont));
            document.Add(new Paragraph(" "));

            // ----- Overall statistics table -----
            document.Add(new Paragraph("OVERALL STATISTICS", boldFont));
            var statsTable = new PdfPTable(2) { WidthPercentage = 100 };
            AddStatRow(statsTable, "Total Records", data.TotalCount.ToString());
            AddStatRow(statsTable, "Completed", FormatCountAndPercent(data.CompletedCount, data.TotalCount));
            AddStatRow(statsTable, "Delayed", FormatCountAndPercent(data.DelayedCount, data.TotalCount));
            AddStatRow(statsTable, "Pending", FormatCountAndPercent(data.PendingCount, data.TotalCount));
            document.Add(statsTable);
            document.Add(new Paragraph(" "));

            // ----- Breakdown by sitio -----
            if (data.SitioSummaries.Any())
            {
                document.Add(new Paragraph("SCHEDULES BY SITIO", boldFont));
                var sitioTable = new PdfPTable(5) { WidthPercentage = 100 };
                foreach (var header in new[] { "Sitio", "Total", "Completed", "Delayed", "Pending" })
                    sitioTable.AddCell(new PdfPCell(new Phrase(header, boldFont)));

                foreach (var item in data.SitioSummaries)
                {
                    sitioTable.AddCell(item.SitioName);
                    sitioTable.AddCell(item.Total.ToString());
                    sitioTable.AddCell(item.Completed.ToString());
                    sitioTable.AddCell(item.Delayed.ToString());
                    sitioTable.AddCell(item.Pending.ToString());
                }
                document.Add(sitioTable);
                document.Add(new Paragraph(" "));
            }

            // ----- Sitios with the most delays (top 3) - helps spot problem areas -----
            var mostDelayed = data.SitioSummaries
                .Where(s => s.Delayed > 0)
                .OrderByDescending(s => s.Delayed)
                .Take(3)
                .ToList();

            if (mostDelayed.Any())
            {
                document.Add(new Paragraph("SITIOS WITH MOST DELAYS", boldFont));
                int rank = 1;
                foreach (var item in mostDelayed)
                {
                    document.Add(new Paragraph(
                        $"{rank}. {item.SitioName} - {item.Delayed} delayed ({item.DelayRate:F0}% delay rate)", normalFont));
                    rank++;
                }
                document.Add(new Paragraph(" "));
            }

            // ----- Monthly trend -----
            if (data.Trends.Any())
            {
                document.Add(new Paragraph("MONTHLY TREND", boldFont));
                var trendTable = new PdfPTable(5) { WidthPercentage = 100 };
                foreach (var header in new[] { "Month", "Total", "Completed", "Delayed", "Pending" })
                    trendTable.AddCell(new PdfPCell(new Phrase(header, boldFont)));

                foreach (var month in data.Trends)
                {
                    trendTable.AddCell(month.MonthYear);
                    trendTable.AddCell(month.Total.ToString());
                    trendTable.AddCell(month.Completed.ToString());
                    trendTable.AddCell(month.Delayed.ToString());
                    trendTable.AddCell(month.Pending.ToString());
                }
                document.Add(trendTable);
            }

            document.Close();
            return stream.ToArray();
        }

        // ---------- Collection Summary: Excel ----------

        private byte[] GenerateCollectionReportExcel(CollectionReportData data)
        {
            using var package = new ExcelPackage();
            var ws = package.Workbook.Worksheets.Add("Collection Report");

            ws.Cells["A1"].Value = "COLLECTION SUMMARY REPORT";
            ws.Cells["A1"].Style.Font.Size = 16;
            ws.Cells["A1"].Style.Font.Bold = true;
            ws.Cells["A2"].Value = "Barangay Tisa";
            ws.Cells["A3"].Value = $"Generated By: {data.GeneratedBy}";
            ws.Cells["A4"].Value = $"Generated On: {data.GeneratedDate:MMMM dd, yyyy h:mm tt}";
            ws.Cells["A5"].Value = $"Date Range: {FormatDate(data.StartDate)} - {FormatDate(data.EndDate)}";

            ws.Cells["A7"].Value = "OVERALL STATISTICS";
            ws.Cells["A7"].Style.Font.Bold = true;
            ws.Cells["A8"].Value = "Total Records";       ws.Cells["B8"].Value = data.TotalCount;
            ws.Cells["A9"].Value = "Completed";            ws.Cells["B9"].Value = FormatCountAndPercent(data.CompletedCount, data.TotalCount);
            ws.Cells["A10"].Value = "Delayed";             ws.Cells["B10"].Value = FormatCountAndPercent(data.DelayedCount, data.TotalCount);
            ws.Cells["A11"].Value = "Pending";             ws.Cells["B11"].Value = FormatCountAndPercent(data.PendingCount, data.TotalCount);

            if (data.SitioSummaries.Any())
            {
                ws.Cells["A13"].Value = "SCHEDULES BY SITIO";
                ws.Cells["A13"].Style.Font.Bold = true;

                var headers = new[] { "Sitio", "Total", "Completed", "Delayed", "Pending" };
                for (int i = 0; i < headers.Length; i++)
                    ws.Cells[14, i + 1].Value = headers[i];

                int row = 15;
                foreach (var item in data.SitioSummaries)
                {
                    ws.Cells[row, 1].Value = item.SitioName;
                    ws.Cells[row, 2].Value = item.Total;
                    ws.Cells[row, 3].Value = item.Completed;
                    ws.Cells[row, 4].Value = item.Delayed;
                    ws.Cells[row, 5].Value = item.Pending;
                    row++;
                }

                // ----- Monthly trend, placed 2 rows below the sitio table -----
                if (data.Trends.Any())
                {
                    row += 1;
                    ws.Cells[$"A{row}"].Value = "MONTHLY TREND";
                    ws.Cells[$"A{row}"].Style.Font.Bold = true;
                    row++;

                    var trendHeaders = new[] { "Month", "Total", "Completed", "Delayed", "Pending" };
                    for (int i = 0; i < trendHeaders.Length; i++)
                        ws.Cells[row, i + 1].Value = trendHeaders[i];
                    row++;

                    foreach (var month in data.Trends)
                    {
                        ws.Cells[row, 1].Value = month.MonthYear;
                        ws.Cells[row, 2].Value = month.Total;
                        ws.Cells[row, 3].Value = month.Completed;
                        ws.Cells[row, 4].Value = month.Delayed;
                        ws.Cells[row, 5].Value = month.Pending;
                        row++;
                    }
                }
            }

            ws.Cells.AutoFitColumns();
            return package.GetAsByteArray();
        }

        // ---------- Complaint Summary: PDF ----------

        private byte[] GenerateComplaintReportPdf(ComplaintReportData data)
        {
            using var stream = new MemoryStream();
            var document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.GetInstance(document, stream);
            document.Open();

            var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 11);
            var boldFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);

            document.Add(new Paragraph("COMPLAINT SUMMARY REPORT", titleFont) { Alignment = Element.ALIGN_CENTER });
            document.Add(new Paragraph("Barangay Tisa", normalFont) { Alignment = Element.ALIGN_CENTER });
            document.Add(new Paragraph(" "));

            document.Add(new Paragraph($"Generated By: {data.GeneratedBy}", normalFont));
            document.Add(new Paragraph($"Generated On: {data.GeneratedDate:MMMM dd, yyyy h:mm tt}", normalFont));
            document.Add(new Paragraph($"Date Range: {FormatDate(data.StartDate)} - {FormatDate(data.EndDate)}", normalFont));
            document.Add(new Paragraph(" "));

            // ----- Overall statistics -----
            document.Add(new Paragraph("OVERALL STATISTICS", boldFont));
            var statsTable = new PdfPTable(2) { WidthPercentage = 100 };
            AddStatRow(statsTable, "Total Complaints", data.TotalComplaints.ToString());
            AddStatRow(statsTable, "Awaiting Review", FormatCountAndPercent(data.AwaitingReviewCount, data.TotalComplaints));
            AddStatRow(statsTable, "Ongoing", FormatCountAndPercent(data.OngoingCount, data.TotalComplaints));
            AddStatRow(statsTable, "Accomplished", FormatCountAndPercent(data.AccomplishedCount, data.TotalComplaints));
            document.Add(statsTable);
            document.Add(new Paragraph(" "));

            // ----- By complaint type -----
            if (data.ComplaintTypeSummaries.Any())
            {
                document.Add(new Paragraph("COMPLAINTS BY TYPE", boldFont));
                var typeTable = new PdfPTable(2) { WidthPercentage = 100 };
                typeTable.AddCell(new PdfPCell(new Phrase("Complaint Type", boldFont)));
                typeTable.AddCell(new PdfPCell(new Phrase("Count", boldFont)));
                foreach (var item in data.ComplaintTypeSummaries)
                {
                    typeTable.AddCell(item.ComplaintType);
                    typeTable.AddCell(item.Count.ToString());
                }
                document.Add(typeTable);
                document.Add(new Paragraph(" "));
            }

            // ----- By sitio -----
            if (data.SitioSummaries.Any())
            {
                document.Add(new Paragraph("COMPLAINTS BY SITIO", boldFont));
                var sitioTable = new PdfPTable(5) { WidthPercentage = 100 };
                foreach (var header in new[] { "Sitio", "Total", "Awaiting Review", "Ongoing", "Accomplished" })
                    sitioTable.AddCell(new PdfPCell(new Phrase(header, boldFont)));

                foreach (var item in data.SitioSummaries.OrderByDescending(s => s.Total))
                {
                    sitioTable.AddCell(item.SitioName);
                    sitioTable.AddCell(item.Total.ToString());
                    sitioTable.AddCell(item.AwaitingReview.ToString());
                    sitioTable.AddCell(item.Ongoing.ToString());
                    sitioTable.AddCell(item.Accomplished.ToString());
                }
                document.Add(sitioTable);
                document.Add(new Paragraph(" "));
            }

            // ----- Frequently affected areas (top 5) - the whole point of this report -----
            var topSitios = data.SitioSummaries.OrderByDescending(s => s.Total).Take(5).ToList();
            if (topSitios.Any())
            {
                document.Add(new Paragraph("FREQUENTLY AFFECTED AREAS", boldFont));
                int rank = 1;
                foreach (var item in topSitios)
                {
                    document.Add(new Paragraph(
                        $"{rank}. {item.SitioName} - {item.Total} complaints ({item.PercentageOfTotal:F0}% of total)", normalFont));
                    rank++;
                }
                document.Add(new Paragraph(" "));
            }

            // ----- Monthly trend -----
            if (data.Trends.Any())
            {
                document.Add(new Paragraph("MONTHLY TREND", boldFont));
                foreach (var month in data.Trends)
                {
                    // Show "+27% increase" / "-10% decrease" after the count when we have
                    // a previous month to compare to; otherwise just show the count.
                    string changeText = "";
                    if (month.PercentChangeFromPreviousMonth.HasValue)
                    {
                        var change = month.PercentChangeFromPreviousMonth.Value;
                        var direction = change >= 0 ? "increase" : "decrease";
                        changeText = $" ({(change >= 0 ? "+" : "")}{change:F0}% {direction})";
                    }
                    document.Add(new Paragraph($"{month.MonthYear} : {month.Complaints} complaints{changeText}", normalFont));
                }
            }

            document.Close();
            return stream.ToArray();
        }

        // ---------- Complaint Summary: Excel ----------

        private byte[] GenerateComplaintReportExcel(ComplaintReportData data)
        {
            using var package = new ExcelPackage();
            var ws = package.Workbook.Worksheets.Add("Complaint Report");

            ws.Cells["A1"].Value = "COMPLAINT SUMMARY REPORT";
            ws.Cells["A1"].Style.Font.Size = 16;
            ws.Cells["A1"].Style.Font.Bold = true;
            ws.Cells["A2"].Value = "Barangay Tisa";
            ws.Cells["A3"].Value = $"Generated By: {data.GeneratedBy}";
            ws.Cells["A4"].Value = $"Generated On: {data.GeneratedDate:MMMM dd, yyyy h:mm tt}";
            ws.Cells["A5"].Value = $"Date Range: {FormatDate(data.StartDate)} - {FormatDate(data.EndDate)}";

            ws.Cells["A7"].Value = "OVERALL STATISTICS";
            ws.Cells["A7"].Style.Font.Bold = true;
            ws.Cells["A8"].Value = "Total Complaints";  ws.Cells["B8"].Value = data.TotalComplaints;
            ws.Cells["A9"].Value = "Awaiting Review";    ws.Cells["B9"].Value = FormatCountAndPercent(data.AwaitingReviewCount, data.TotalComplaints);
            ws.Cells["A10"].Value = "Ongoing";           ws.Cells["B10"].Value = FormatCountAndPercent(data.OngoingCount, data.TotalComplaints);
            ws.Cells["A11"].Value = "Accomplished";      ws.Cells["B11"].Value = FormatCountAndPercent(data.AccomplishedCount, data.TotalComplaints);

            int nextRow = 13;
            if (data.ComplaintTypeSummaries.Any())
            {
                ws.Cells[$"A{nextRow}"].Value = "COMPLAINTS BY TYPE";
                ws.Cells[$"A{nextRow}"].Style.Font.Bold = true;
                nextRow++;
                ws.Cells[$"A{nextRow}"].Value = "Complaint Type";
                ws.Cells[$"B{nextRow}"].Value = "Count";
                nextRow++;
                foreach (var item in data.ComplaintTypeSummaries)
                {
                    ws.Cells[$"A{nextRow}"].Value = item.ComplaintType;
                    ws.Cells[$"B{nextRow}"].Value = item.Count;
                    nextRow++;
                }
                nextRow++; // blank row before the next section
            }

            if (data.SitioSummaries.Any())
            {
                ws.Cells[$"A{nextRow}"].Value = "COMPLAINTS BY SITIO";
                ws.Cells[$"A{nextRow}"].Style.Font.Bold = true;
                nextRow++;

                var headers = new[] { "Sitio", "Total", "Awaiting Review", "Ongoing", "Accomplished" };
                for (int i = 0; i < headers.Length; i++)
                    ws.Cells[nextRow, i + 1].Value = headers[i];
                nextRow++;

                foreach (var item in data.SitioSummaries.OrderByDescending(s => s.Total))
                {
                    ws.Cells[nextRow, 1].Value = item.SitioName;
                    ws.Cells[nextRow, 2].Value = item.Total;
                    ws.Cells[nextRow, 3].Value = item.AwaitingReview;
                    ws.Cells[nextRow, 4].Value = item.Ongoing;
                    ws.Cells[nextRow, 5].Value = item.Accomplished;
                    nextRow++;
                }
                nextRow++; // blank row before the next section
            }

            // ----- Monthly trend -----
            if (data.Trends.Any())
            {
                ws.Cells[$"A{nextRow}"].Value = "MONTHLY TREND";
                ws.Cells[$"A{nextRow}"].Style.Font.Bold = true;
                nextRow++;

                ws.Cells[$"A{nextRow}"].Value = "Month";
                ws.Cells[$"B{nextRow}"].Value = "Complaints";
                ws.Cells[$"C{nextRow}"].Value = "% Change vs Previous Month";
                nextRow++;

                foreach (var month in data.Trends)
                {
                    ws.Cells[$"A{nextRow}"].Value = month.MonthYear;
                    ws.Cells[$"B{nextRow}"].Value = month.Complaints;
                    ws.Cells[$"C{nextRow}"].Value = month.PercentChangeFromPreviousMonth.HasValue
                        ? $"{(month.PercentChangeFromPreviousMonth.Value >= 0 ? "+" : "")}{month.PercentChangeFromPreviousMonth.Value:F0}%"
                        : "-";
                    nextRow++;
                }
            }

            ws.Cells.AutoFitColumns();
            return package.GetAsByteArray();
        }

        // ---------- Small shared helpers ----------

        // Adds a "Label | Value" row to a 2-column PDF table
        private void AddStatRow(PdfPTable table, string label, string value)
        {
            table.AddCell(label);
            table.AddCell(value);
        }

        // Turns (8, 45) into "8 (18%)" - used everywhere we show a count + percentage
        private string FormatCountAndPercent(int count, int total)
        {
            double percent = total > 0 ? (double)count / total * 100 : 0;
            return $"{count} ({percent:F0}%)";
        }

        // Shows "Not specified" instead of a blank when no date filter was chosen
        private string FormatDate(DateTime? date)
        {
            return date.HasValue ? date.Value.ToString("MMMM dd, yyyy") : "Not specified";
        }
    }
}
