using System.ComponentModel.DataAnnotations;

namespace TisaWasteManagement.Models
{
    public class Collector
    {
        // Primary key - auto-generated by the database
        [Key]
        public int CollectorId { get; set; }

        // Required field - collector must have a first name
        // Max 50 characters to match the database column definition
        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; } = string.Empty;

        // Required field - collector must have a last name
        // Max 50 characters to match the database column definition
        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; } = string.Empty;

        // Required field - must be exactly 11 digits
        // Uses regex to validate Philippine mobile format (starts with 09, followed by 9 digits)
        // Database has a unique index to prevent duplicate contact numbers
        [Required]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone number must be exactly 11 digits.")]
        [RegularExpression("^09\\d{9}$", ErrorMessage = "Phone number must be a valid Philippine mobile number starting with 09 and contain only digits.")]
        [Display(Name = "Contact Number")]
        public string ContactNumber { get; set; } = string.Empty;

        // Required field - collector must have a registered address
        // Max 200 characters for complete address information
        [Required]
        [StringLength(200)]
        [Display(Name = "Address")]
        public string Address { get; set; } = string.Empty;

        // Comma-separated list of days off (e.g. "Monday,Wednesday")
        [Display(Name = "Days Off")]
        public string? DaysOff { get; set; }

        // Role of this garbage crew member - either "Collector" or "Driver".
        // Defaults to "Collector" so existing records without a role still work.
        [Required]
        [StringLength(20)]
        [Display(Name = "Role")]
        public string Role { get; set; } = "Collector";
    }
}