using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace TisaWasteManagement.Models
{
    /// <summary>
    /// Represents a waste-related complaint filed by a resident.
    /// Residents can submit complaints without logging in.
    /// </summary>
    public class Complaint
    {
        // Primary key - auto-generated by the database
        [Key]
        public int ComplaintId { get; set; }

        // Optional - Resident's full name. If left blank, the controller
        // saves it as "Anonymous" before writing to the database.
        [StringLength(100, ErrorMessage = "Name cannot exceed 100 characters.")]
        [Display(Name = "Resident Name")]
        public string? ResidentName { get; set; } = string.Empty;

        // Required - Contact number for follow-ups
        [Required(ErrorMessage = "Contact Number is required.")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone number must be exactly 11 digits.")]
        [RegularExpression("^09\\d{9}$", ErrorMessage = "Phone number must be a valid Philippine mobile number starting with 09.")]
        [Display(Name = "Contact Number")]
        public string ContactNumber { get; set; } = string.Empty;

        // Required - Which sitio the complaint is about
        [Required(ErrorMessage = "Please select a Sitio.")]
        [Display(Name = "Sitio")]
        public int SitioId { get; set; }

        // Required - Type of complaint (Missed Collection, Illegal Dumping, Other)
        [Required(ErrorMessage = "Please select a Complaint Type.")]
        [StringLength(50)]
        [Display(Name = "Complaint Type")]
        public string ComplaintType { get; set; } = string.Empty;

        // Required - Detailed description of the complaint
        [Required(ErrorMessage = "Please provide details about your complaint.")]
        [StringLength(1000, ErrorMessage = "Details cannot exceed 1000 characters.")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Details")]
        public string Details { get; set; } = string.Empty;

        // Auto-generated unique ticket number for tracking
        // Format: TISA-YYYYMMDD-XXXX (e.g., TISA-20260718-0001)
        [Display(Name = "Ticket Number")]
        public string TicketNumber { get; set; } = string.Empty;

        // Status workflow: Awaiting Review → Ongoing → Accomplished
        // Default is "Awaiting Review" for new complaints
        [StringLength(20)]
        [Display(Name = "Status")]
        public string Status { get; set; } = "Awaiting Review";

        // When the complaint was filed
        [Display(Name = "Filed Date")]
        public DateTime FiledDate { get; set; } = DateTime.Now;

        // When the status was last updated
        [Display(Name = "Last Updated")]
        public DateTime? UpdatedDate { get; set; }

        // We only store the FILE NAME here (e.g. "3f6b1c2e.jpg"), not the full path
        // and not the image bytes themselves. This is the same approach used by the
        // Announcement and BulletinBoardImage modules.
        // The picture itself lives in wwwroot/images/complaints/.
        // The full web path is built in the views as: /images/complaints/{ImageFileName}
        [StringLength(255)]
        [Display(Name = "Image File Name")]
        public string? ImageFileName { get; set; }

        // Navigation property to Sitio
        [ValidateNever]
        [ForeignKey("SitioId")]
        public virtual Sitio Sitio { get; set; }

        // Helper flag to check if a photo was attached to this complaint.
        [NotMapped]
        public bool HasImage => !string.IsNullOrEmpty(ImageFileName);

        // Helper property that builds the web path to the picture, for use in
        // <img src="..."> tags. Returns null when there's no picture.
        // Example result: "/images/complaints/3f6b1c2e.jpg"
        [NotMapped]
        public string? ImageUrl => HasImage ? $"/images/complaints/{ImageFileName}" : null;

        // Helper property to display the status in a user-friendly way
        [NotMapped]
        public string StatusDisplayName
        {
            get
            {
                return Status switch
                {
                    // "Urgent" was removed from the label - it now just shows "Awaiting Review".
                    "Awaiting Review" => "Awaiting Review",
                    "Ongoing" => "Ongoing - Being Addressed",
                    "Accomplished" => "Accomplished - Resolved",
                    _ => Status
                };
            }
        }
    }
}