using System.ComponentModel.DataAnnotations;

namespace TisaWasteManagement.Models
{
    public class GarbageTruck
    {
        // Primary key - auto-generated by the database
        [Key]
        public int TruckId { get; set; }

        // Optional field - a new truck may only have an MV File Number
        // until the LTO releases its plate number
        // Max 20 characters (e.g., "ABC-1234" format)
        [StringLength(20)]
        [Display(Name = "Plate Number")]
        public string? PlateNumber { get; set; }

        // Optional field - used when the plate number is not yet available
        // Must be exactly 15 digits when provided
        // Database has a unique index to prevent duplicate MV numbers
        [StringLength(15, ErrorMessage = "MV number must be exactly 15 digits.")]
        [Display(Name = "MV File Number")]
        public string? MVFileNumber { get; set; }

        // Required field - truck must have an operational status
        // Options: Active, Inactive, Maintenance
        // Default value is "Active" for newly registered trucks
        [Required]
        [StringLength(20)]
        [Display(Name = "Status")]
        public string StatusFlag { get; set; } = "Active";
    }
}