using System.ComponentModel.DataAnnotations;

namespace TisaWasteManagement.Models
{
    public class Sitio
    {
        // Primary key - auto-generated by the database
        [Key]
        public int SitioId { get; set; }

        // Required field - cannot be empty
        // Max 100 characters as defined in the database table
        // Display name shown on form labels and error messages
        [Required]
        [StringLength(100)]
        [Display(Name = "Sitio Name")]
        public string SitioName { get; set; } = string.Empty;
    }
}