using System;
using System.ComponentModel.DataAnnotations;

namespace TisaWasteManagement.Models
{
    /// <summary>
    /// SMS Module
    /// -----------
    /// This model represents ONE row in the SmsLog database table.
    /// Every time the system tries to send an SMS (whether it succeeds
    /// or fails), we save one SmsLog record so Admins can see a history
    /// of what was sent, to whom, and whether it worked.
    /// </summary>
    public class SmsLog
    {
        // Primary key - auto-generated by the database (1, 2, 3, ...)
        [Key]
        public int SmsLogId { get; set; }

        // The resident's phone number the SMS was sent to (e.g. "09171234567")
        [Required]
        [StringLength(11)]
        [Display(Name = "Recipient Number")]
        public string RecipientNumber { get; set; } = string.Empty;

        // The actual text message that was sent
        [Required]
        [StringLength(500)]
        [Display(Name = "Message")]
        public string Message { get; set; } = string.Empty;

        // A short label describing WHY the SMS was sent.
        // For this module we only use "ComplaintUpdate", but the field
        // is flexible in case other modules want to send SMS later.
        [StringLength(50)]
        [Display(Name = "Notification Type")]
        public string NotificationType { get; set; } = string.Empty;

        // Optional link back to the record that triggered this SMS
        // (for us, this will be the ComplaintId).
        [Display(Name = "Reference ID")]
        public int? ReferenceId { get; set; }

        // "Sent" or "Failed" - lets the Admin quickly see what worked
        [StringLength(50)]
        [Display(Name = "Status")]
        public string Status { get; set; } = "Pending";

        // When this SMS attempt happened
        [Display(Name = "Sent Date")]
        public DateTime SentDate { get; set; } = DateTime.Now;

        // Raw response text from the SMS provider (TextBee), or the
        // error message if it failed. Useful for troubleshooting.
        [StringLength(1000)]
        [Display(Name = "Response")]
        public string? Response { get; set; }

        // Who/what triggered the SMS. For this module it's always
        // "System" since SMS is sent automatically on status change.
        [StringLength(100)]
        [Display(Name = "Sent By")]
        public string? SentBy { get; set; }
    }
}
